// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6gCTA4ymvpxyfH72ivHmezcmZDwD8ITA',
    appId: '1:602042931306:web:0f7af9e3fd7a8871251213',
    messagingSenderId: '602042931306',
    projectId: 'crud-abaad',
    authDomain: 'crud-abaad.firebaseapp.com',
    storageBucket: 'crud-abaad.appspot.com',
    measurementId: 'G-KFJ3TTP570',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACQ_6hPhaQH0XzbjTy0vVeh495Md5dapc',
    appId: '1:602042931306:android:0ac865f6bb1b25ca251213',
    messagingSenderId: '602042931306',
    projectId: 'crud-abaad',
    storageBucket: 'crud-abaad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_TLUvBQtMUIMjo2Au7dXwREG2_adswNU',
    appId: '1:602042931306:ios:da12fc2cdf56250a251213',
    messagingSenderId: '602042931306',
    projectId: 'crud-abaad',
    storageBucket: 'crud-abaad.appspot.com',
    iosBundleId: 'com.example.homenestshop',
  );
}
